config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: %i[new create show destroy]
  resources :attendances, only: %i[create destroy index edit new] 
  resources :users
  resources :events
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'events#index'

  get 'sign_up', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout' => 'sessions#destroy', as: 'logout'
  get 'profile' => 'users#show', as: 'profile'
  get 'attend' => 'attendances#create', as: 'attend'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, :description, :location, presence: true
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
  has_many :attendances
  has_many :attendees, class_name: 'User', through: :attendances, source: :user, dependent: :delete_all

  scope :upcoming_events, -> { where(['events.date > ?', Date.today]) }
  scope :previous_events, -> { where(['events.date <= ?', Date.today]) }
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, :email, presence: true
  has_many :events, foreign_key: 'user_id'
  has_many :attendances, foreign_key: ':user_id'
  has_many :attended_events, class_name: 'Event', through: :attendances

  def user_comming_events
    events.upcoming_events
  end

  def user_past_events
    events.previous_events
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :display_button_new
  helper_method :display_button_log
  helper_method :display_username
  helper_method :user_validation

  def current_user
    User.find_by(id: session[:user_id])
  end

  def display_username
    return current_user.username if current_user
  end

  def display_button_log
    if current_user.present?
      "<a class='button is-info' href='/profile'>Profile</a>".html_safe
    else
      "<a class='button is-success' href='/login'>Sign in</a>".html_safe
    end
  end

  def user_validation
    if current_user.present?
      "<a class='button is-danger' href='/logout'>Log out</a>".html_safe
    else
      "<a class='button is-success' href='/sign_up'>Sign up</a>".html_safe
    end
  end

  def display_button_new
    return "<a class='button is-success' href='/events/new'>NEW EVENT</a>".html_safe if current_user.present?
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_attendance, only: %i[show edit update destroy]

  # GET /attendances
  # GET /attendances.json
  def index
    @attendances = Attendance.all
  end

  # GET /attendances/1
  # GET /attendances/1.json
  def show; end

  # GET /attendances/new
  def new
    @attendance = Attendance.new
  end

  # GET /attendances/1/edit
  def edit; end

  # POST /attendances
  # POST /attendances.json
  def create
    @event = Event.find(params[:event_id])
    @event.attendees << current_user
    if @event.save
      redirect_to root_path
      flash[:notice] = 'Your are checked in to this Event'
    else
      format.html { render :new }
      format.json { render json: @attendance.errors, status: :unprocessable_entity }
    end
  end

  def update
    respond_to do |format|
      if @attendance.update(attendance_params)
        format.html { redirect_to @attendance, notice: 'Attendance was successfully updated.' }
        format.json { render :show, status: :ok, location: @attendance }
      else
        format.html { render :edit }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendances/1
  # DELETE /attendances/1.json
  def destroy
    @attendance.destroy
    respond_to do |format|
      format.html { redirect_to attendances_url, notice: 'Attendance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_attendance
    @attendance = Attendance.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def attendance_params
    params.require(:attendance).permit(:user_id, :event_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
    @creator = User.find(@event.user_id).username
    @attendances = Attendance.all
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit; end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:name, :date, :description, :location)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params['email'])
    if user
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to root_path, alert: 'Not a user'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(session[:user_id])
    @events = Event.all
    @attendances = Attendance.all
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render 'new'
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(session[:user_id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:username, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendances/_form.html.erb
<%= form_with(model: @attendance, local: true) do |form| %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.collection_select(:user_id, User.all, :id, :username,
                  { multiple: true, size: 3 }, class: "select mr-3" )%>
  </div>

  <div class="field">
    <%= form.label :event_id %>
    <%= form.collection_select(:event_id, Event.all, :id, :name,
                  { multiple: true, size: 3 }, class: "select mr-3" )%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/attendances/edit.html.erb
<h1>Editing Attendance</h1>

<%= render 'form', attendance: @attendance %>

<%= link_to 'Show', @attendance %> |
<%= link_to 'Back', attendances_path %>

app/views/attendances/index.html.erb
<div class="section">
    <div class="container">
	    <div class="columns is-centered">
		    <div class="column is-4 translucid">
          <h1>Attendances</h1>
          
          <table>
            <thead>
              <tr>
                <th>User</th>
                <th>Event</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @attendances.each do |attendance| %>
                <tr>
                  <td><%= attendance.user.username %></td>
                  <td><%= attendance.event.name %></td>
                  <td><%= link_to 'Show', attendance %></td>
                  <td><%= link_to 'Edit', edit_attendance_path(attendance) %></td>
                  <td><%= link_to 'Destroy', attendance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
</div>

app/views/attendances/new.html.erb
<div class="section">
  <div class="container">
	  <div class="columns is-centered">
		  <div class="column is-4 translucid">
        <h1>New Attendance</h1>
        <table>
          <thead>
            <tr>
              <th>Name</th>
              <th>Date</th>
              <th>Location</th>
              <th>Description</th>
              <th colspan="3"></th>
            </tr>
          </thead>
        
          <tbody>
            <%= render 'form' %>
          </tbody>
        </table>
        <%= link_to 'Back', attendances_path %>
      </div>
    </div>
  </div>
</div>

app/views/attendances/show.html.erb
<div class="section">
	<div class="container">
	  <div class="columns is-centered">
		  <div class="column is-4 translucid">
        <p>
          <strong>User:</strong>
          <%= @attendance.user_id %>
        </p>

        <p>
          <strong>Event:</strong>
          <%= @attendance.event_id %>
        </p>

        <%= link_to 'Edit', edit_attendance_path(@attendance) %> |
        <%= link_to 'Back', attendances_path %>
      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_area :location %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="section">
    <div class="container">
	    <div class="columns is-centered">
		    <div class="column is-4 translucid">
                <h1 class='title is-3'>Editing Event</h1>
                <%= render 'form', event: @event , class: 'mt-4'%>

                <%= link_to 'Show', @event %> |
                <%= link_to 'Back', events_path %>
            </div>
        </div>
    </div>
</div>

app/views/events/index.html.erb
<div class="section">
	<div class="container">
	<div class="columns is-centered">
		<div class="column is-7 translucid">
      <h2 class="columns is-centered has-text-black title is-3">Upcoming Events</h2>
      <table class="table is-bordered is-fullwidth">
        <thead>
          <tr class="table_color">
            <th class=" has-text-white">Name</th>
            <th class=" has-text-white">Date</th>
            <th class=" has-text-white">Location</th>
            <th class=" has-text-white">Description</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @events.upcoming_events.each do |event| %>
            <tr>
              <td><%= event.name %></td>
              <td><%= event.date %></td>
              <td><%= event.location %></td>
              <td><%= event.description %></td>
              <td><%= link_to 'Show', event %></td>
              <% if current_user.present? %>
                <% if event.user_id == current_user.id %>
                  <td><%= link_to 'Edit', edit_event_path(event) %></td>
                  <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                <% end %>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
      <h2 class="columns is-centered has-text-black title is-3">Previous Events</h2>
      <table class="table is-bordered is-fullwidth is-hoverable">
        <thead>
          <tr class="table_color">
            <th class=" has-text-white">Name</th>
            <th class=" has-text-white">Date</th>
            <th class=" has-text-white">Location</th>
            <th class=" has-text-white">Description</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @events.previous_events.each do |event| %>
            <tr>
              <td><%= event.name %></td>
              <td><%= event.date %></td>
              <td><%= event.location %></td>
              <td><%= event.description %></td>
              <td><%= link_to 'Show', event %></td>
              <% if current_user.present? %>
                <% if event.user_id == current_user.id %>
                  <td><%= link_to 'Edit', edit_event_path(event) %></td>
                  <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                <% end %>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
		</div>
		</div>
	</div>
</div>

app/views/events/new.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-4 translucid">
				<h1>New Event</h1>

				<%= render 'form', event: @event %>

				<%= link_to 'Back', events_path %>
			</div>
		</div>
	</div>
</div>

app/views/events/show.html.erb
<div class="section">
	<div class="container translucid">
    <div class="columns is-centered">

      <div class="column is-4">
        
        <p id="notice"><%= notice %></p>

        <p>
          <strong>Name:</strong>
          <%= @event.name %>
        </p>

        <p>
          <strong>Date:</strong>
          <%= @event.date %>
        </p>

        <p>
          <strong>Location:</strong>
          <%= @event.location %>
        </p>

        <p>
          <strong>Description:</strong>
          <%= @event.description %>
        </p>

        <p>
          <strong>Creator:</strong>
          <%= @creator %>
        </p> 

        <div>
        <% if @event.user_id == current_user.id %>
            <%= link_to 'Edit', edit_event_path(@event) %> |
        <% end %>
        <%= link_to 'Back', events_path %> |
        <%= link_to 'Attend', attend_path(event_id: @event.id) %>

      </div>
      <% if @event.attendances.any? %>
    <div class="columns is-centered">
      <div class="column is-4">
        <table>
          <thead>
            <tr>
              <th>Attendees</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @attendances.each do |attendance| %>
              <tr>
                <td><%= attendance.user.username %></td>
                <td><%= link_to 'Uninvite', attendance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <% else %>
        <h5 class="card-title">No one is coming, yet...</h5>
    <% end %>
		</div>
	</div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar is-dark sticky-top">
    <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
        <h1 class="title is-4">Private Events</h1>
        <% end %>
        <p class="control mt-4">
            <%= display_button_new %>
        </p>
        <div class="navbar-burger burger" data-target="navbarExample">
            <span></span>
            <span></span>
            <span></span>
        </div>
    </div>
    <div id="navbarExample" class="navbar-menu">
        <div class="navbar-end">
            <div class="field is-grouped mt-2 mr-2">
                <div class='field is-grouped mt-2 mr-2'>
                <p class='control'>
                    <%= display_button_log %>
                </p>
                <p class='control'>
                    <%= user_validation %>
                </p>
                </div>
            </div>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-primary global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    <%= render 'layouts/navbar'%>
    <div class="degrade">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |form| %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="section">
    <div class="container">
	    <div class="columns is-centered">
		    <div class="column is-4 translucid">
                <h1>Editing User</h1>

                <%= render 'form', user: @user %>

                <%= link_to 'Show', @user %> |
                <%= link_to 'Back', users_path %>
            </div>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="section">
	<div class="container">
	<div class="columns is-centered ">

		<div class="column is-4 translucid">
            <%= render 'form' %>
			
		</div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="section">
	<div class="container">
	<div class="columns is-centered">

		<div class="column is-7 translucid">
			
      <p id="notice"><%= notice %></p>

      <p class="columns is-centered title is-5"> 
        <strong>Username:</strong>
        <%= @user.username %>
      </p>

      <p class="columns is-centered title is-5">
        <strong>Email:</strong>
        <%= @user.email %>
      </p>
      <div class="columns is-centered title is-5">
      <%= link_to 'Edit', edit_user_path(@user) %> 
      </div>
      
      <h2 class="columns is-centered has-text-black title is-3">Created Upcoming Events</h2>
      <table class="table is-bordered is-fullwidth">
        <thead>
          <tr class="table_color">
            <th class=" has-text-white">Name</th>
            <th class=" has-text-white">Date</th>
            <th class=" has-text-white">Location</th>
            <th class=" has-text-white">Description</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @user.user_comming_events.each do |event| %>
            <tr>
              <td><%= event.name %></td>
              <td><%= event.date %></td>
              <td><%= event.location %></td>
              <td><%= event.description %></td>
              <td><%= link_to 'Show', event %></td>
              <td><%= link_to 'Edit', edit_event_path(event) %></td>
              <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <h2 class="columns is-centered has-text-black title is-3">Created Previous Events</h2>
      <table class="table is-bordered is-fullwidth is-hoverable">
        <thead>
          <tr class="table_color">
            <th class=" has-text-white">Name</th>
            <th class=" has-text-white">Date</th>
            <th class=" has-text-white">Location</th>
            <th class=" has-text-white">Description</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @user.user_past_events.each do |event| %>
            <tr>
              <td><%= event.name %></td>
              <td><%= event.date %></td>
              <td><%= event.location %></td>
              <td><%= event.description %></td>
              <td><%= link_to 'Show', event %></td>
              <td><%= link_to 'Edit', edit_event_path(event) %></td>
              <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
		</div>
		</div>
	</div>
</div>